version: '2'

services:
        nginx:
                image: nginx:1.18
                container_name: nginx
                restart: always
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - /var/www:/var/www
                        - /data/docker/web/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
                        - /data/docker/web/nginx/fastcgi_params:/etc/nginx/fastcgi_params
                        - /data/docker/web/nginx/snippets:/etc/nginx/snippets
                        - /data/docker/web/nginx/conf.d:/etc/nginx/conf.d
                        - /data/docker/web/php/socket:/run/php
                        - /data/docker/web/nginx/logs:/var/log/nginx/
                depends_on:
                        - php73
                        - php55
                networks:
                        - web
        php73:
                image: trumanwl/php:7.3-fpm
                container_name: php73
                volumes:
                        - /var/www:/var/www
                        - /data/docker/web/php/socket:/run/php
                        - /data/docker/web/supervisor/conf.d:/etc/supervisor/conf.d
                networks:
                        - web
        php55:
                image: trumanwl/php:5.5-fpm
                container_name: php55
                volumes:
                        - /var/www:/var/www
                        - /data/docker/web/php/socket:/run/php
                networks:
                        - web
networks:
        web:
                driver: bridge
