version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9191:9090"
