version: '3'

services:
  redis:
    image: redis:6.0
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - redis
    volumes:
      - /data/docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - /data/docker/redis/data:/data
    command:
      redis-server /etc/redis/redis.conf
networks:
  redis:
    driver: bridge